# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Gerard Cristofol
email: gcristofol@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A software developer and architect. 
  Co-founder of http://www.oneboxtm.com 
  Particularity interested in automation, big systems and scalability.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://gcristofol.github.io" # the base hostname & protocol for your site
twitter_username: gcristofol
github_username:  gcristofol

# Build settings
markdown: kramdown
